# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  push:
    branches:
      - bootstrap  # Убедитесь, что указана ваша основная ветка

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21' # Укажите версию Node.js, которая вам нужна

      - name: Install dependencies
        run: npm install

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Build project
        run: npm run build

      - name: Move to docs folder
        run: |
          mkdir -p ./docs
          cp -R ./dist/* ./docs/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GG }}
          publish_dir: ./docs/eer/browser
